"""
Common helper functions for exploratory notebooks.

The goal of this module is to keep notebooks clean and avoid duplicating setup,
dataset loading, saving, and display logic.
"""

from __future__ import annotations

import json
import ast
from pathlib import Path
from typing import Any, Tuple

import pandas as pd

from src.preprocessing.document_loader import (
    dataframe_to_documents,
    load_arxiv_csv,
    load_arxiv_jsonl,
)
from src.preprocessing.text_cleaning import preprocess, preprocess_to_string
from src.utils.project_config import (
    ProjectPaths,
    get_project_paths,
    load_config,
    print_project_context,
)


def setup_notebook() -> Tuple[dict, ProjectPaths]:
    config = load_config()
    paths = get_project_paths(config)
    print_project_context(paths)
    return config, paths


def save_table(df: pd.DataFrame, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return path


def save_json(data: Any, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return path


def display_basic_frame_info(df: pd.DataFrame, name: str = "DataFrame") -> None:
    print(f"{name} shape:", df.shape)
    print(f"{name} columns:", list(df.columns))
    display(df.head())  # noqa: F821


def get_dataset_file(paths: ProjectPaths) -> Path:
    candidates = []

    for pattern in ["*.json", "*.jsonl", "*.csv"]:
        candidates.extend(sorted(paths.data_raw.glob(pattern)))

    if not candidates:
        raise FileNotFoundError(
            "No dataset found in data/raw. Add arxiv-metadata-oai-snapshot.json "
            "or a compatible CSV/JSONL file."
        )

    # Prefer the real arXiv dataset over generated sample files.
    non_sample = [path for path in candidates if "sample" not in path.name.lower()]

    return non_sample[0] if non_sample else candidates[0]


def load_project_documents(config: dict, paths: ProjectPaths):
    dataset_cfg = config.get("dataset", {})
    sample_size = dataset_cfg.get("sample_size")
    categories = dataset_cfg.get("categories")
    seed = config.get("project", {}).get("seed", 42)

    dataset_path = get_dataset_file(paths)
    suffix = dataset_path.suffix.lower()

    if suffix == ".csv":
        df = load_arxiv_csv(
            str(dataset_path),
            sample_size=sample_size,
            categories=categories,
            seed=seed,
        )
    elif suffix in {".json", ".jsonl"}:
        df = load_arxiv_jsonl(
            str(dataset_path),
            sample_size=sample_size,
            categories=categories,
            seed=seed,
        )
    else:
        raise ValueError(f"Unsupported dataset format: {dataset_path.suffix}")

    documents = dataframe_to_documents(df)
    return df, documents, dataset_path


def load_processed_documents(paths: ProjectPaths) -> pd.DataFrame:
    processed_path = paths.data_processed / "processed_documents.csv"

    if not processed_path.exists():
        raise FileNotFoundError(
            "processed_documents.csv not found. Run: "
            "python -m src.pipeline.run_pipeline --skip-embeddings"
        )

    return pd.read_csv(processed_path)


def load_or_create_processed_documents(config, paths):
    """
    Load processed documents generated by the pipeline.
    """
    if paths.processed_documents.exists():
        print(f"Loading processed documents from: {paths.processed_documents}")
        return pd.read_csv(paths.processed_documents)

    raise FileNotFoundError(
        "\nprocessed_documents.csv not found.\n\n"
        "Run the pipeline first:\n"
        "    python -m src.pipeline.run_pipeline --skip-embeddings\n\n"
        f"Expected file:\n"
        f"    {paths.processed_documents}\n"
    )

def parse_token_column(value):
    """
    Convert a token column loaded from CSV into a Python list.

    Supports:
    - actual Python lists
    - string representations of lists
    - whitespace-separated strings
    - NaN values
    """
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    if isinstance(value, str):
        try:
            parsed = ast.literal_eval(value)

            if isinstance(parsed, list):
                return parsed

        except (ValueError, SyntaxError):
            return value.split()

    return []